create table questions (
id Integer PRIMARY KEY GENERATED BY DEFAULT AS identity,
questionType text not null,
answers text not null,
questionText text not null,
responseText text not null,
correctText text,
link text,
linktype text,
quiznum integer references quiz(id) on delete cascade not Null
) 